#!/bin/sh

test -x ./node_modules/.bin/prettier || \
  { printf '[error] ./node_modules/.bin/prettier not installed'; exit 1; }

files=$(git diff --cached --name-only --diff-filter=ACMR | sed 's/ /\\ /g')
test -z "$files" && exit

echo "$files" | xargs ./node_modules/.bin/prettier --ignore-unknown --write
echo "$files" | xargs git add
